-- Mapolos Restaurant Management System
-- Full schema + RPCs. Idempotent: safe to re-run in the Supabase SQL editor.
-- Extends the original restaurant_ordering MVP with tables, a staff-driven order
-- lifecycle, menu CRUD, table/QR management, and expanded analytics.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
set search_path = public, extensions;

-- ---------------------------------------------------------------------------
-- Drop functions (recreated below)
-- ---------------------------------------------------------------------------
drop function if exists public.verify_order_code(text, text);
drop function if exists public.get_admin_orders(text);
drop function if exists public.get_admin_analytics(text);
drop function if exists public.get_admin_analytics_v2(text, timestamptz, timestamptz);
drop function if exists public.get_admin_session(text);
drop function if exists public.admin_sign_out(text);
drop function if exists public.admin_sign_in(text, text);
drop function if exists public.get_order_status(bigint, text);
drop function if exists public.create_order(bigint, text, text, text, jsonb);
drop function if exists public.create_order(bigint, bigint, text, text, text, jsonb);
drop function if exists public.expire_pending_orders();
drop function if exists public._require_admin_session(text);
drop function if exists public.resolve_table(uuid);
drop function if exists public.advance_order_status(text, bigint, text);
drop function if exists public.cancel_order(text, bigint);
drop function if exists public.list_menu_items(text);
drop function if exists public.create_menu_item(text, jsonb);
drop function if exists public.update_menu_item(text, bigint, jsonb);
drop function if exists public.set_menu_item_availability(text, bigint, boolean);
drop function if exists public.delete_menu_item(text, bigint);
drop function if exists public.list_tables(text);
drop function if exists public.create_table(text, jsonb);
drop function if exists public.update_table(text, bigint, jsonb);
drop function if exists public.delete_table(text, bigint);

-- ---------------------------------------------------------------------------
-- Base tables (created only if this is a fresh database)
-- ---------------------------------------------------------------------------
create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  description text not null,
  location text not null,
  sample_table varchar(20) not null default 'T-01',
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  category varchar(80) not null default 'Chef Signatures',
  name varchar(140) not null,
  description text not null,
  price numeric(10, 2) not null check (price > 0),
  ar_model_url text not null default '',
  image_url text not null default '',
  is_available boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  customer_name varchar(120),
  table_number varchar(20),
  special_request text,
  status varchar(40) not null default 'pending_verification',
  total_price numeric(10, 2) not null check (total_price >= 0),
  is_verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id),
  quantity integer not null check (quantity > 0),
  price_at_time numeric(10, 2) not null check (price_at_time >= 0)
);

create table if not exists public.order_verifications (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  code varchar(6) not null unique,
  expires_at timestamptz not null,
  verified_at timestamptz
);

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  email varchar(190) not null unique,
  password_hash text not null,
  role varchar(40) not null default 'manager',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  admin_id bigint not null references public.admins(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- New: physical tables with QR tokens
-- ---------------------------------------------------------------------------
create table if not exists public.tables (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  table_number varchar(20) not null,
  label varchar(80) not null default '',
  seats integer not null default 2 check (seats > 0),
  qr_token uuid not null unique default gen_random_uuid(),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (restaurant_id, table_number)
);

-- ---------------------------------------------------------------------------
-- Schema upgrades for existing databases (idempotent column adds)
-- ---------------------------------------------------------------------------
alter table public.orders add column if not exists table_id bigint references public.tables(id) on delete set null;
alter table public.orders add column if not exists confirmed_at timestamptz;
alter table public.orders add column if not exists prep_started_at timestamptz;
alter table public.orders add column if not exists ready_at timestamptz;
alter table public.orders add column if not exists served_at timestamptz;

-- Relax the status check to include the kitchen lifecycle states.
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check
  check (status in (
    'pending_verification', 'confirmed', 'preparing', 'ready', 'served', 'expired', 'cancelled'
  ));

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
create index if not exists idx_menu_items_restaurant_available
  on public.menu_items(restaurant_id, is_available, category, display_order);
create index if not exists idx_orders_restaurant_created
  on public.orders(restaurant_id, created_at desc);
create index if not exists idx_order_items_order
  on public.order_items(order_id);
create index if not exists idx_order_verifications_code
  on public.order_verifications(code, expires_at);
create index if not exists idx_admin_sessions_token_hash
  on public.admin_sessions(token_hash, expires_at);
create index if not exists idx_tables_restaurant
  on public.tables(restaurant_id, is_active);
create index if not exists idx_tables_qr_token
  on public.tables(qr_token);

-- ---------------------------------------------------------------------------
-- Helper: expire stale pending orders
-- ---------------------------------------------------------------------------
create or replace function public.expire_pending_orders()
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  updated_count integer := 0;
begin
  update public.orders
  set status = 'expired',
      is_verified = false
  where status = 'pending_verification'
    and exists (
      select 1
      from public.order_verifications ov
      where ov.order_id = public.orders.id
        and ov.verified_at is null
        and ov.expires_at <= now()
    );

  get diagnostics updated_count = row_count;
  return updated_count;
end;
$$;

-- ---------------------------------------------------------------------------
-- Helper: validate an admin session token, return the admin context
-- ---------------------------------------------------------------------------
create or replace function public._require_admin_session(p_session_token text)
returns table (
  admin_id bigint,
  restaurant_id bigint,
  email varchar,
  role varchar
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  normalized_token text := trim(coalesce(p_session_token, ''));
  hashed_token text;
begin
  if normalized_token = '' then
    raise exception 'Please sign in to continue.';
  end if;

  hashed_token := encode(digest(normalized_token, 'sha256'), 'hex');

  return query
  with matched_session as (
    select s.admin_id
    from public.admin_sessions s
    where s.token_hash = hashed_token
      and s.expires_at > now()
  )
  select a.id, a.restaurant_id, a.email, a.role
  from matched_session ms
  join public.admins a
    on a.id = ms.admin_id
  where a.is_active = true;

  if not found then
    raise exception 'Your admin session has expired. Please sign in again.';
  end if;

  update public.admin_sessions
  set last_seen_at = now()
  where token_hash = hashed_token;
end;
$$;

-- ---------------------------------------------------------------------------
-- Customer: resolve a table from its QR token
-- ---------------------------------------------------------------------------
create or replace function public.resolve_table(p_qr_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  result jsonb;
begin
  select jsonb_build_object(
    'tableId', t.id,
    'tableNumber', t.table_number,
    'restaurantId', t.restaurant_id,
    'restaurant', jsonb_build_object(
      'id', r.id,
      'name', r.name,
      'description', r.description,
      'location', r.location,
      'sampleTable', r.sample_table
    )
  )
  into result
  from public.tables t
  join public.restaurants r on r.id = t.restaurant_id
  where t.qr_token = p_qr_token
    and t.is_active = true;

  if result is null then
    raise exception 'Table not found or inactive.';
  end if;

  return result;
end;
$$;

-- ---------------------------------------------------------------------------
-- Customer: create an order (now table-aware)
-- ---------------------------------------------------------------------------
create or replace function public.create_order(
  p_restaurant_id bigint,
  p_table_id bigint default null,
  p_table_number text default null,
  p_customer_name text default null,
  p_special_request text default null,
  p_items jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_order_id bigint;
  verification_code varchar(6);
  verification_expires_at timestamptz := now() + interval '10 minutes';
  requested_count integer := 0;
  matched_count integer := 0;
  computed_total numeric(10, 2) := 0;
  resolved_table_number text := nullif(trim(coalesce(p_table_number, '')), '');
begin
  perform public.expire_pending_orders();

  if not exists (select 1 from public.restaurants where id = p_restaurant_id) then
    raise exception 'Restaurant not found.';
  end if;

  -- Resolve table number from table_id when provided.
  if p_table_id is not null then
    select t.table_number into resolved_table_number
    from public.tables t
    where t.id = p_table_id and t.restaurant_id = p_restaurant_id;
  end if;

  select count(*) into requested_count from jsonb_array_elements(p_items);
  if requested_count = 0 then
    raise exception 'Add at least one dish before placing an order.';
  end if;

  with requested_items as (
    select
      (item ->> 'menuItemId')::bigint as menu_item_id,
      greatest(1, coalesce((item ->> 'quantity')::integer, 0)) as quantity
    from jsonb_array_elements(p_items) item
  )
  select count(*), coalesce(sum(mi.price * ri.quantity), 0)
  into matched_count, computed_total
  from requested_items ri
  join public.menu_items mi
    on mi.id = ri.menu_item_id
   and mi.restaurant_id = p_restaurant_id
   and mi.is_available = true;

  if matched_count <> requested_count then
    raise exception 'One or more selected dishes are not available.';
  end if;

  loop
    verification_code := lpad((floor(random() * 900000) + 100000)::int::text, 6, '0');
    exit when not exists (
      select 1 from public.order_verifications where code = verification_code
    );
  end loop;

  insert into public.orders (
    restaurant_id, table_id, customer_name, table_number,
    special_request, status, total_price, is_verified
  )
  values (
    p_restaurant_id,
    p_table_id,
    nullif(trim(coalesce(p_customer_name, '')), ''),
    resolved_table_number,
    nullif(trim(coalesce(p_special_request, '')), ''),
    'pending_verification',
    computed_total,
    false
  )
  returning id into new_order_id;

  with requested_items as (
    select
      (item ->> 'menuItemId')::bigint as menu_item_id,
      greatest(1, coalesce((item ->> 'quantity')::integer, 0)) as quantity
    from jsonb_array_elements(p_items) item
  )
  insert into public.order_items (order_id, menu_item_id, quantity, price_at_time)
  select new_order_id, mi.id, ri.quantity, mi.price
  from requested_items ri
  join public.menu_items mi
    on mi.id = ri.menu_item_id
   and mi.restaurant_id = p_restaurant_id
   and mi.is_available = true;

  insert into public.order_verifications (order_id, code, expires_at)
  values (new_order_id, verification_code, verification_expires_at);

  return jsonb_build_object(
    'orderId', new_order_id,
    'verificationCode', verification_code,
    'expiresAt', verification_expires_at,
    'status', 'pending_verification',
    'totalPrice', computed_total
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Customer: poll order status (now exposes lifecycle timestamps)
-- ---------------------------------------------------------------------------
create or replace function public.get_order_status(p_order_id bigint, p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  normalized_code text := trim(coalesce(p_code, ''));
  order_payload jsonb;
begin
  perform public.expire_pending_orders();

  select jsonb_build_object(
    'orderId', o.id,
    'restaurantId', o.restaurant_id,
    'customerName', o.customer_name,
    'tableNumber', o.table_number,
    'specialRequest', o.special_request,
    'status', o.status,
    'isVerified', o.is_verified,
    'totalPrice', o.total_price,
    'createdAt', o.created_at,
    'confirmedAt', o.confirmed_at,
    'prepStartedAt', o.prep_started_at,
    'readyAt', o.ready_at,
    'servedAt', o.served_at,
    'expiresAt', ov.expires_at,
    'verifiedAt', ov.verified_at,
    'items', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'menuItemId', mi.id,
            'name', mi.name,
            'quantity', oi.quantity,
            'priceAtTime', oi.price_at_time,
            'lineTotal', oi.quantity * oi.price_at_time
          ) order by mi.name
        )
        from public.order_items oi
        join public.menu_items mi on mi.id = oi.menu_item_id
        where oi.order_id = o.id
      ),
      '[]'::jsonb
    )
  )
  into order_payload
  from public.orders o
  join public.order_verifications ov on ov.order_id = o.id
  where o.id = p_order_id and ov.code = normalized_code;

  if order_payload is null then
    raise exception 'Order not found.';
  end if;

  return order_payload;
end;
$$;

-- ---------------------------------------------------------------------------
-- Admin auth
-- ---------------------------------------------------------------------------
create or replace function public.admin_sign_in(p_email text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  matched_admin record;
  raw_session_token text;
  hashed_token text;
begin
  select a.id, a.restaurant_id, a.email, a.role, r.name as restaurant_name
  into matched_admin
  from public.admins a
  join public.restaurants r on r.id = a.restaurant_id
  where lower(a.email) = lower(trim(coalesce(p_email, '')))
    and a.is_active = true
    and a.password_hash = crypt(coalesce(p_password, ''), a.password_hash);

  if matched_admin is null then
    raise exception 'Incorrect email or password.';
  end if;

  raw_session_token := gen_random_uuid()::text || gen_random_uuid()::text;
  hashed_token := encode(digest(raw_session_token, 'sha256'), 'hex');

  insert into public.admin_sessions (admin_id, token_hash, expires_at)
  values (matched_admin.id, hashed_token, now() + interval '7 days');

  return jsonb_build_object(
    'sessionToken', raw_session_token,
    'admin', jsonb_build_object(
      'id', matched_admin.id,
      'email', matched_admin.email,
      'role', matched_admin.role,
      'restaurantId', matched_admin.restaurant_id,
      'restaurantName', matched_admin.restaurant_name
    )
  );
end;
$$;

create or replace function public.admin_sign_out(p_session_token text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  hashed_token text := encode(digest(trim(coalesce(p_session_token, '')), 'sha256'), 'hex');
begin
  delete from public.admin_sessions where token_hash = hashed_token;
  return true;
end;
$$;

create or replace function public.get_admin_session(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  return (
    select jsonb_build_object(
      'admin', jsonb_build_object('id', a.id, 'email', a.email, 'role', a.role),
      'restaurant', jsonb_build_object(
        'id', r.id, 'name', r.name, 'description', r.description,
        'location', r.location, 'sampleTable', r.sample_table
      )
    )
    from public.admins a
    join public.restaurants r on r.id = a.restaurant_id
    where a.id = session_row.admin_id
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: verify a customer's order code -> moves order to 'confirmed'
-- ---------------------------------------------------------------------------
create or replace function public.verify_order_code(p_session_token text, p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  normalized_code text := trim(coalesce(p_code, ''));
  matched_order record;
begin
  perform public.expire_pending_orders();

  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  select o.id, o.status, ov.expires_at, ov.verified_at
  into matched_order
  from public.orders o
  join public.order_verifications ov on ov.order_id = o.id
  where o.restaurant_id = session_row.restaurant_id
    and ov.code = normalized_code;

  if matched_order is null then
    raise exception 'Code not found for this restaurant.';
  end if;

  if matched_order.verified_at is not null or matched_order.status <> 'pending_verification' then
    raise exception 'This order is already verified.';
  end if;

  if matched_order.expires_at <= now() then
    update public.orders set status = 'expired', is_verified = false where id = matched_order.id;
    raise exception 'This verification code has expired.';
  end if;

  update public.order_verifications set verified_at = now() where order_id = matched_order.id;
  update public.orders
  set status = 'confirmed', is_verified = true, confirmed_at = now()
  where id = matched_order.id;

  return jsonb_build_object('orderId', matched_order.id, 'status', 'confirmed', 'verifiedAt', now());
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: advance an order through the kitchen lifecycle
-- ---------------------------------------------------------------------------
create or replace function public.advance_order_status(
  p_session_token text,
  p_order_id bigint,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  current_status text;
  next_status text := trim(coalesce(p_status, ''));
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  select status into current_status
  from public.orders
  where id = p_order_id and restaurant_id = session_row.restaurant_id;

  if current_status is null then
    raise exception 'Order not found for this restaurant.';
  end if;

  -- Allowed forward transitions.
  if not (
    (current_status = 'confirmed' and next_status = 'preparing') or
    (current_status = 'preparing' and next_status = 'ready') or
    (current_status = 'ready' and next_status = 'served')
  ) then
    raise exception 'Cannot move order from % to %.', current_status, next_status;
  end if;

  update public.orders
  set status = next_status,
      prep_started_at = case when next_status = 'preparing' then now() else prep_started_at end,
      ready_at = case when next_status = 'ready' then now() else ready_at end,
      served_at = case when next_status = 'served' then now() else served_at end
  where id = p_order_id;

  return jsonb_build_object('orderId', p_order_id, 'status', next_status);
end;
$$;

create or replace function public.cancel_order(p_session_token text, p_order_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  current_status text;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  select status into current_status
  from public.orders
  where id = p_order_id and restaurant_id = session_row.restaurant_id;

  if current_status is null then
    raise exception 'Order not found for this restaurant.';
  end if;

  if current_status in ('served', 'cancelled', 'expired') then
    raise exception 'Order cannot be cancelled from its current state.';
  end if;

  update public.orders set status = 'cancelled' where id = p_order_id;
  return jsonb_build_object('orderId', p_order_id, 'status', 'cancelled');
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: live order feed
-- ---------------------------------------------------------------------------
create or replace function public.get_admin_orders(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
begin
  perform public.expire_pending_orders();

  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  return coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', o.id,
          'customerName', o.customer_name,
          'tableNumber', o.table_number,
          'specialRequest', o.special_request,
          'status', o.status,
          'totalPrice', o.total_price,
          'isVerified', o.is_verified,
          'createdAt', o.created_at,
          'confirmedAt', o.confirmed_at,
          'prepStartedAt', o.prep_started_at,
          'readyAt', o.ready_at,
          'servedAt', o.served_at,
          'expiresAt', ov.expires_at,
          'items', coalesce(
            (
              select jsonb_agg(
                jsonb_build_object(
                  'menuItemId', mi.id,
                  'name', mi.name,
                  'quantity', oi.quantity,
                  'priceAtTime', oi.price_at_time,
                  'lineTotal', oi.quantity * oi.price_at_time
                ) order by mi.name
              )
              from public.order_items oi
              join public.menu_items mi on mi.id = oi.menu_item_id
              where oi.order_id = o.id
            ),
            '[]'::jsonb
          )
        ) order by o.created_at desc
      )
      from (
        select * from public.orders
        where restaurant_id = session_row.restaurant_id
        order by created_at desc
        limit 50
      ) o
      join public.order_verifications ov on ov.order_id = o.id
    ),
    '[]'::jsonb
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: expanded analytics with a date range
-- ---------------------------------------------------------------------------
create or replace function public.get_admin_analytics_v2(
  p_session_token text,
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  range_from timestamptz := coalesce(p_from, now() - interval '30 days');
  range_to timestamptz := coalesce(p_to, now());
begin
  perform public.expire_pending_orders();

  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  return jsonb_build_object(
    'range', jsonb_build_object('from', range_from, 'to', range_to),
    'metrics', (
      select jsonb_build_object(
        'ordersToday', count(*) filter (where o.created_at >= date_trunc('day', now())),
        'revenueToday', coalesce(sum(o.total_price) filter (where o.created_at >= date_trunc('day', now()) and o.is_verified = true), 0),
        'pendingVerification', count(*) filter (where o.status = 'pending_verification'),
        'avgOrderValue', coalesce(avg(o.total_price) filter (where o.is_verified = true), 0),
        'verificationRate', case when count(*) = 0 then 0 else round((count(*) filter (where o.is_verified = true))::numeric / count(*)::numeric * 100, 1) end,
        'avgPrepMinutes', coalesce(round(avg(extract(epoch from (o.served_at - o.confirmed_at)) / 60) filter (where o.served_at is not null and o.confirmed_at is not null)::numeric, 1), 0),
        'tableTurnover', count(distinct o.table_id) filter (where o.created_at >= date_trunc('day', now()) and o.table_id is not null)
      )
      from public.orders o
      where o.restaurant_id = session_row.restaurant_id
    ),
    'dailyRevenue', (
      select coalesce(jsonb_agg(
        jsonb_build_object(
          'label', to_char(day_series.day_value, 'Dy'),
          'date', day_series.day_value,
          'revenue', coalesce(day_totals.revenue, 0),
          'orders', coalesce(day_totals.orders, 0)
        ) order by day_series.day_value
      ), '[]'::jsonb)
      from (
        select generate_series(current_date - interval '6 days', current_date, interval '1 day')::date as day_value
      ) day_series
      left join (
        select date(created_at) as order_day, count(*) as orders,
               sum(total_price) filter (where is_verified = true) as revenue
        from public.orders
        where restaurant_id = session_row.restaurant_id
          and created_at >= current_date - interval '6 days'
        group by date(created_at)
      ) day_totals on day_totals.order_day = day_series.day_value
    ),
    'hourly', (
      select coalesce(jsonb_agg(
        jsonb_build_object('hour', h.hour, 'orders', coalesce(hc.orders, 0), 'revenue', coalesce(hc.revenue, 0))
        order by h.hour
      ), '[]'::jsonb)
      from generate_series(0, 23) as h(hour)
      left join (
        select extract(hour from created_at)::int as hour, count(*) as orders,
               sum(total_price) filter (where is_verified = true) as revenue
        from public.orders
        where restaurant_id = session_row.restaurant_id
          and created_at between range_from and range_to
        group by 1
      ) hc on hc.hour = h.hour
    ),
    'categoryBreakdown', (
      select coalesce(jsonb_agg(
        jsonb_build_object('category', cat.category, 'quantity', cat.quantity, 'revenue', cat.revenue)
        order by cat.revenue desc
      ), '[]'::jsonb)
      from (
        select mi.category, sum(oi.quantity) as quantity, sum(oi.quantity * oi.price_at_time) as revenue
        from public.order_items oi
        join public.orders o on o.id = oi.order_id
        join public.menu_items mi on mi.id = oi.menu_item_id
        where o.restaurant_id = session_row.restaurant_id
          and o.created_at between range_from and range_to
        group by mi.category
      ) cat
    ),
    'statusFunnel', (
      select coalesce(jsonb_object_agg(status, cnt), '{}'::jsonb)
      from (
        select status, count(*) as cnt
        from public.orders
        where restaurant_id = session_row.restaurant_id
          and created_at between range_from and range_to
        group by status
      ) sf
    ),
    'topItems', (
      select coalesce(jsonb_agg(
        jsonb_build_object('name', item_stats.name, 'quantity', item_stats.quantity, 'revenue', item_stats.revenue)
        order by item_stats.quantity desc, item_stats.revenue desc
      ), '[]'::jsonb)
      from (
        select mi.name, sum(oi.quantity) as quantity, sum(oi.quantity * oi.price_at_time) as revenue
        from public.order_items oi
        join public.orders o on o.id = oi.order_id
        join public.menu_items mi on mi.id = oi.menu_item_id
        where o.restaurant_id = session_row.restaurant_id
          and o.created_at between range_from and range_to
        group by mi.name
        order by quantity desc, revenue desc
        limit 8
      ) item_stats
    )
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: menu management (CRUD)
-- ---------------------------------------------------------------------------
create or replace function public.list_menu_items(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  return coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', mi.id, 'restaurantId', mi.restaurant_id, 'category', mi.category,
          'name', mi.name, 'description', mi.description, 'price', mi.price,
          'arModelUrl', mi.ar_model_url, 'imageUrl', mi.image_url,
          'isAvailable', mi.is_available, 'displayOrder', mi.display_order
        ) order by mi.category, mi.display_order
      )
      from public.menu_items mi
      where mi.restaurant_id = session_row.restaurant_id
    ),
    '[]'::jsonb
  );
end;
$$;

create or replace function public.create_menu_item(p_session_token text, p_item jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  new_id bigint;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  insert into public.menu_items (
    restaurant_id, category, name, description, price,
    ar_model_url, image_url, is_available, display_order
  )
  values (
    session_row.restaurant_id,
    coalesce(nullif(trim(p_item ->> 'category'), ''), 'Menu'),
    trim(p_item ->> 'name'),
    coalesce(p_item ->> 'description', ''),
    coalesce((p_item ->> 'price')::numeric, 0),
    coalesce(p_item ->> 'arModelUrl', ''),
    coalesce(p_item ->> 'imageUrl', ''),
    coalesce((p_item ->> 'isAvailable')::boolean, true),
    coalesce((p_item ->> 'displayOrder')::integer, 0)
  )
  returning id into new_id;

  return jsonb_build_object('id', new_id);
end;
$$;

create or replace function public.update_menu_item(p_session_token text, p_id bigint, p_item jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  update public.menu_items mi
  set category = coalesce(nullif(trim(p_item ->> 'category'), ''), mi.category),
      name = coalesce(nullif(trim(p_item ->> 'name'), ''), mi.name),
      description = coalesce(p_item ->> 'description', mi.description),
      price = coalesce((p_item ->> 'price')::numeric, mi.price),
      ar_model_url = coalesce(p_item ->> 'arModelUrl', mi.ar_model_url),
      image_url = coalesce(p_item ->> 'imageUrl', mi.image_url),
      is_available = coalesce((p_item ->> 'isAvailable')::boolean, mi.is_available),
      display_order = coalesce((p_item ->> 'displayOrder')::integer, mi.display_order)
  where mi.id = p_id and mi.restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then
    raise exception 'Menu item not found for this restaurant.';
  end if;

  return jsonb_build_object('id', p_id);
end;
$$;

create or replace function public.set_menu_item_availability(p_session_token text, p_id bigint, p_available boolean)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  update public.menu_items
  set is_available = p_available
  where id = p_id and restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then
    raise exception 'Menu item not found for this restaurant.';
  end if;

  return jsonb_build_object('id', p_id, 'isAvailable', p_available);
end;
$$;

create or replace function public.delete_menu_item(p_session_token text, p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  delete from public.menu_items
  where id = p_id and restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then
    raise exception 'Menu item not found for this restaurant.';
  end if;

  return jsonb_build_object('id', p_id, 'deleted', true);
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: table management (CRUD)
-- ---------------------------------------------------------------------------
create or replace function public.list_tables(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  return coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', t.id, 'tableNumber', t.table_number, 'label', t.label,
          'seats', t.seats, 'qrToken', t.qr_token, 'isActive', t.is_active
        ) order by t.table_number
      )
      from public.tables t
      where t.restaurant_id = session_row.restaurant_id
    ),
    '[]'::jsonb
  );
end;
$$;

create or replace function public.create_table(p_session_token text, p_table jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  new_id bigint;
  new_token uuid;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  insert into public.tables (restaurant_id, table_number, label, seats, is_active)
  values (
    session_row.restaurant_id,
    trim(p_table ->> 'tableNumber'),
    coalesce(p_table ->> 'label', ''),
    coalesce((p_table ->> 'seats')::integer, 2),
    coalesce((p_table ->> 'isActive')::boolean, true)
  )
  returning id, qr_token into new_id, new_token;

  return jsonb_build_object('id', new_id, 'qrToken', new_token);
end;
$$;

create or replace function public.update_table(p_session_token text, p_id bigint, p_table jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  update public.tables t
  set table_number = coalesce(nullif(trim(p_table ->> 'tableNumber'), ''), t.table_number),
      label = coalesce(p_table ->> 'label', t.label),
      seats = coalesce((p_table ->> 'seats')::integer, t.seats),
      is_active = coalesce((p_table ->> 'isActive')::boolean, t.is_active)
  where t.id = p_id and t.restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then
    raise exception 'Table not found for this restaurant.';
  end if;

  return jsonb_build_object('id', p_id);
end;
$$;

create or replace function public.delete_table(p_session_token text, p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  delete from public.tables
  where id = p_id and restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then
    raise exception 'Table not found for this restaurant.';
  end if;

  return jsonb_build_object('id', p_id, 'deleted', true);
end;
$$;

-- ---------------------------------------------------------------------------
-- Row level security + grants
-- ---------------------------------------------------------------------------
alter table public.restaurants enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_verifications enable row level security;
alter table public.admins enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.tables enable row level security;

revoke all on public.orders from anon, authenticated;
revoke all on public.order_items from anon, authenticated;
revoke all on public.order_verifications from anon, authenticated;
revoke all on public.admins from anon, authenticated;
revoke all on public.admin_sessions from anon, authenticated;
revoke all on public.tables from anon, authenticated;

grant select on public.restaurants to anon, authenticated;
grant select on public.menu_items to anon, authenticated;

drop policy if exists "Public can read restaurants" on public.restaurants;
create policy "Public can read restaurants"
  on public.restaurants for select to anon, authenticated using (true);

drop policy if exists "Public can read available menu items" on public.menu_items;
create policy "Public can read available menu items"
  on public.menu_items for select to anon, authenticated using (is_available = true);

grant execute on function public.expire_pending_orders() to anon, authenticated;
grant execute on function public.resolve_table(uuid) to anon, authenticated;
grant execute on function public.create_order(bigint, bigint, text, text, text, jsonb) to anon, authenticated;
grant execute on function public.get_order_status(bigint, text) to anon, authenticated;
grant execute on function public.admin_sign_in(text, text) to anon, authenticated;
grant execute on function public.admin_sign_out(text) to anon, authenticated;
grant execute on function public.get_admin_session(text) to anon, authenticated;
grant execute on function public.get_admin_analytics_v2(text, timestamptz, timestamptz) to anon, authenticated;
grant execute on function public.get_admin_orders(text) to anon, authenticated;
grant execute on function public.verify_order_code(text, text) to anon, authenticated;
grant execute on function public.advance_order_status(text, bigint, text) to anon, authenticated;
grant execute on function public.cancel_order(text, bigint) to anon, authenticated;
grant execute on function public.list_menu_items(text) to anon, authenticated;
grant execute on function public.create_menu_item(text, jsonb) to anon, authenticated;
grant execute on function public.update_menu_item(text, bigint, jsonb) to anon, authenticated;
grant execute on function public.set_menu_item_availability(text, bigint, boolean) to anon, authenticated;
grant execute on function public.delete_menu_item(text, bigint) to anon, authenticated;
grant execute on function public.list_tables(text) to anon, authenticated;
grant execute on function public.create_table(text, jsonb) to anon, authenticated;
grant execute on function public.update_table(text, bigint, jsonb) to anon, authenticated;
grant execute on function public.delete_table(text, bigint) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Seed data (only when empty)
-- ---------------------------------------------------------------------------
insert into public.restaurants (id, name, description, location, sample_table)
select 1, 'Mapolos Downtown',
  'A contemporary Italian dining room with fast QR ordering, elegant course pacing, and immersive AR previews for signature dishes.',
  'Main Boulevard, Karachi', 'T-12'
where not exists (select 1 from public.restaurants where id = 1);

insert into public.restaurants (id, name, description, location, sample_table)
select 2, 'Mapolos Garden',
  'A lighter courtyard expression of Mapolos with calm lunch service and the same hero plates rendered in AR.',
  'Clifton Block 5, Karachi', 'G-04'
where not exists (select 1 from public.restaurants where id = 2);

select setval(pg_get_serial_sequence('public.restaurants', 'id'), (select max(id) from public.restaurants), true);

insert into public.menu_items (id, restaurant_id, category, name, description, price, ar_model_url, image_url, is_available, display_order)
select * from (values
  (1, 1, 'Chef Signatures', 'Chicken Alfredo', 'Tender grilled chicken over fresh fettuccine with parmesan cream, lemon zest, and a glossy sauce finish.', 1690.00, '/models/alfredo.glb', '/images/alfredo-card.svg', true, 1),
  (2, 1, 'Chef Signatures', 'Tarragon Chicken', 'Slow-roasted chicken in a fragrant tarragon cream reduction with roasted vegetables and herb oil.', 1490.00, '/models/tarragon.glb', '/images/tarragon-card.svg', true, 2),
  (3, 2, 'Chef Signatures', 'Chicken Alfredo', 'Tender grilled chicken over fresh fettuccine with parmesan cream, lemon zest, and a glossy sauce finish.', 1690.00, '/models/alfredo.glb', '/images/alfredo-card.svg', true, 1),
  (4, 2, 'Chef Signatures', 'Tarragon Chicken', 'Slow-roasted chicken in a fragrant tarragon cream reduction with roasted vegetables and herb oil.', 1490.00, '/models/tarragon.glb', '/images/tarragon-card.svg', true, 2)
) as seed(id, restaurant_id, category, name, description, price, ar_model_url, image_url, is_available, display_order)
where not exists (select 1 from public.menu_items);

select setval(pg_get_serial_sequence('public.menu_items', 'id'), (select max(id) from public.menu_items), true);

insert into public.admins (id, restaurant_id, email, password_hash, role, is_active)
select 1, 1, 'manager@mapolos.com', crypt('Mapolos@123', gen_salt('bf', 10)), 'owner', true
where not exists (select 1 from public.admins where id = 1);

insert into public.admins (id, restaurant_id, email, password_hash, role, is_active)
select 2, 2, 'garden@mapolos.com', crypt('Garden@123', gen_salt('bf', 10)), 'manager', true
where not exists (select 1 from public.admins where id = 2);

select setval(pg_get_serial_sequence('public.admins', 'id'), (select max(id) from public.admins), true);

-- Seed a handful of tables for restaurant 1 if none exist.
insert into public.tables (restaurant_id, table_number, label, seats)
select 1, 'T-' || lpad(g::text, 2, '0'), 'Main floor', 4
from generate_series(1, 12) g
where not exists (select 1 from public.tables where restaurant_id = 1);

insert into public.tables (restaurant_id, table_number, label, seats)
select 2, 'G-' || lpad(g::text, 2, '0'), 'Courtyard', 2
from generate_series(1, 8) g
where not exists (select 1 from public.tables where restaurant_id = 2);

-- ============================================================================
-- Restaurant Management System — Full extension
-- ============================================================================

drop function if exists public.create_pos_order(text, jsonb);
drop function if exists public.update_table_status(text, bigint, text);
drop function if exists public.list_reservations(text, date, date);
drop function if exists public.create_reservation(text, jsonb);
drop function if exists public.update_reservation_status(text, bigint, text);
drop function if exists public.delete_reservation(text, bigint);
drop function if exists public.list_inventory(text);
drop function if exists public.create_inventory_item(text, jsonb);
drop function if exists public.update_inventory_item(text, bigint, jsonb);
drop function if exists public.adjust_inventory_stock(text, bigint, numeric);
drop function if exists public.delete_inventory_item(text, bigint);
drop function if exists public.list_staff(text);
drop function if exists public.create_staff_member(text, jsonb);
drop function if exists public.update_staff_member(text, bigint, jsonb);
drop function if exists public.delete_staff_member(text, bigint);
drop function if exists public.clock_in_staff(text, bigint);
drop function if exists public.clock_out_staff(text, bigint);
drop function if exists public.get_active_shifts(text);

-- Table status and floor layout columns
alter table public.tables add column if not exists status varchar(30) not null default 'available';
alter table public.tables drop constraint if exists tables_status_check;
alter table public.tables add constraint tables_status_check
  check (status in ('available', 'occupied', 'reserved', 'cleaning'));
alter table public.tables add column if not exists floor_x integer not null default 0;
alter table public.tables add column if not exists floor_y integer not null default 0;

-- Reservations
create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  table_id bigint references public.tables(id) on delete set null,
  guest_name varchar(120) not null,
  guest_phone varchar(30),
  party_size integer not null check (party_size > 0),
  reserved_at timestamptz not null,
  duration_minutes integer not null default 90,
  status varchar(30) not null default 'confirmed',
  notes text,
  created_at timestamptz not null default now(),
  constraint reservations_status_check
    check (status in ('confirmed','seated','completed','cancelled','no_show'))
);

-- Inventory items
create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  name varchar(140) not null,
  category varchar(80) not null default 'General',
  unit varchar(30) not null default 'pcs',
  quantity_on_hand numeric(10,2) not null default 0 check (quantity_on_hand >= 0),
  low_stock_threshold numeric(10,2) not null default 10,
  cost_per_unit numeric(10,2) not null default 0 check (cost_per_unit >= 0),
  supplier varchar(140),
  last_restocked_at timestamptz,
  created_at timestamptz not null default now()
);

-- Staff members (separate from admin logins)
create table if not exists public.staff_members (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  name varchar(120) not null,
  role varchar(60) not null default 'server',
  phone varchar(30),
  hourly_rate numeric(8,2),
  is_active boolean not null default true,
  hired_at date not null default current_date,
  created_at timestamptz not null default now()
);

-- Shifts (clock in/out)
create table if not exists public.shifts (
  id bigint generated by default as identity primary key,
  staff_member_id bigint not null references public.staff_members(id) on delete cascade,
  restaurant_id bigint not null,
  clock_in timestamptz not null default now(),
  clock_out timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_reservations_restaurant_date
  on public.reservations(restaurant_id, reserved_at);
create index if not exists idx_inventory_restaurant
  on public.inventory_items(restaurant_id, category);
create index if not exists idx_staff_restaurant
  on public.staff_members(restaurant_id, is_active);
create index if not exists idx_shifts_date
  on public.shifts(restaurant_id, clock_in);

-- ---------------------------------------------------------------------------
-- POS: create a staff-initiated order (auto-confirmed, no QR verification)
-- ---------------------------------------------------------------------------
create or replace function public.create_pos_order(p_session_token text, p_order jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  new_order_id bigint;
  requested_count integer := 0;
  matched_count integer := 0;
  computed_total numeric(10,2) := 0;
  p_items jsonb := coalesce(p_order -> 'items', '[]'::jsonb);
  p_table_id bigint := nullif((p_order ->> 'tableId'), '')::bigint;
  p_customer_name text := nullif(trim(coalesce(p_order ->> 'customerName','')), '');
  p_table_number text := nullif(trim(coalesce(p_order ->> 'tableNumber','')), '');
  p_special_request text := nullif(trim(coalesce(p_order ->> 'specialRequest','')), '');
  resolved_table_number text := p_table_number;
  dummy_code varchar(6);
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  if p_table_id is not null then
    select table_number into resolved_table_number
    from public.tables
    where id = p_table_id and restaurant_id = session_row.restaurant_id;
  end if;

  select count(*) into requested_count from jsonb_array_elements(p_items);
  if requested_count = 0 then
    raise exception 'Add at least one item before charging.';
  end if;

  with ri as (
    select (item->>'menuItemId')::bigint as menu_item_id,
           greatest(1, coalesce((item->>'quantity')::integer,0)) as quantity
    from jsonb_array_elements(p_items) item
  )
  select count(*), coalesce(sum(mi.price * ri.quantity), 0)
  into matched_count, computed_total
  from ri
  join public.menu_items mi on mi.id = ri.menu_item_id
    and mi.restaurant_id = session_row.restaurant_id
    and mi.is_available = true;

  if matched_count <> requested_count then
    raise exception 'One or more selected items are not available.';
  end if;

  insert into public.orders (
    restaurant_id, table_id, customer_name, table_number,
    special_request, status, total_price, is_verified, confirmed_at
  )
  values (
    session_row.restaurant_id, p_table_id, p_customer_name,
    resolved_table_number, p_special_request,
    'confirmed', computed_total, true, now()
  )
  returning id into new_order_id;

  with ri as (
    select (item->>'menuItemId')::bigint as menu_item_id,
           greatest(1, coalesce((item->>'quantity')::integer,0)) as quantity
    from jsonb_array_elements(p_items) item
  )
  insert into public.order_items (order_id, menu_item_id, quantity, price_at_time)
  select new_order_id, mi.id, ri.quantity, mi.price
  from ri
  join public.menu_items mi on mi.id = ri.menu_item_id
    and mi.restaurant_id = session_row.restaurant_id
    and mi.is_available = true;

  -- POS orders don't need a verification code but the FK requires one.
  loop
    dummy_code := lpad((floor(random() * 900000) + 100000)::int::text, 6, '0');
    exit when not exists (select 1 from public.order_verifications where code = dummy_code);
  end loop;
  insert into public.order_verifications (order_id, code, expires_at, verified_at)
  values (new_order_id, dummy_code, now() + interval '1 second', now());

  -- Mark table as occupied
  if p_table_id is not null then
    update public.tables set status = 'occupied'
    where id = p_table_id and restaurant_id = session_row.restaurant_id;
  end if;

  return jsonb_build_object(
    'orderId', new_order_id,
    'status', 'confirmed',
    'totalPrice', computed_total
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: change a table's floor status
-- ---------------------------------------------------------------------------
create or replace function public.update_table_status(
  p_session_token text, p_table_id bigint, p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  update public.tables
  set status = p_status
  where id = p_table_id and restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then raise exception 'Table not found.'; end if;

  return jsonb_build_object('id', p_table_id, 'status', p_status);
end;
$$;

-- ---------------------------------------------------------------------------
-- Reservations CRUD
-- ---------------------------------------------------------------------------
create or replace function public.list_reservations(
  p_session_token text, p_from date default null, p_to date default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  range_from timestamptz := coalesce(p_from::timestamptz, date_trunc('day', now()));
  range_to timestamptz := coalesce((p_to + interval '1 day')::timestamptz, date_trunc('day', now()) + interval '7 days');
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  return coalesce(
    (select jsonb_agg(
      jsonb_build_object(
        'id', r.id, 'tableId', r.table_id,
        'tableNumber', t.table_number,
        'guestName', r.guest_name, 'guestPhone', r.guest_phone,
        'partySize', r.party_size, 'reservedAt', r.reserved_at,
        'durationMinutes', r.duration_minutes, 'status', r.status,
        'notes', r.notes, 'createdAt', r.created_at
      ) order by r.reserved_at
    )
    from public.reservations r
    left join public.tables t on t.id = r.table_id
    where r.restaurant_id = session_row.restaurant_id
      and r.reserved_at >= range_from and r.reserved_at < range_to),
    '[]'::jsonb
  );
end;
$$;

create or replace function public.create_reservation(p_session_token text, p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  new_id bigint;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  insert into public.reservations (
    restaurant_id, table_id, guest_name, guest_phone, party_size,
    reserved_at, duration_minutes, status, notes
  )
  values (
    session_row.restaurant_id,
    nullif((p_data->>'tableId')::text, '')::bigint,
    trim(p_data->>'guestName'),
    nullif(trim(coalesce(p_data->>'guestPhone','')), ''),
    coalesce((p_data->>'partySize')::integer, 2),
    (p_data->>'reservedAt')::timestamptz,
    coalesce((p_data->>'durationMinutes')::integer, 90),
    coalesce(nullif(p_data->>'status',''), 'confirmed'),
    nullif(trim(coalesce(p_data->>'notes','')), '')
  )
  returning id into new_id;

  return jsonb_build_object('id', new_id);
end;
$$;

create or replace function public.update_reservation_status(
  p_session_token text, p_id bigint, p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  update public.reservations
  set status = p_status
  where id = p_id and restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then raise exception 'Reservation not found.'; end if;

  return jsonb_build_object('id', p_id, 'status', p_status);
end;
$$;

create or replace function public.delete_reservation(p_session_token text, p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  delete from public.reservations
  where id = p_id and restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then raise exception 'Reservation not found.'; end if;

  return jsonb_build_object('id', p_id, 'deleted', true);
end;
$$;

-- ---------------------------------------------------------------------------
-- Inventory CRUD
-- ---------------------------------------------------------------------------
create or replace function public.list_inventory(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  return coalesce(
    (select jsonb_agg(jsonb_build_object(
      'id', i.id, 'name', i.name, 'category', i.category, 'unit', i.unit,
      'quantityOnHand', i.quantity_on_hand, 'lowStockThreshold', i.low_stock_threshold,
      'costPerUnit', i.cost_per_unit, 'supplier', i.supplier,
      'lastRestockedAt', i.last_restocked_at, 'createdAt', i.created_at,
      'isLow', i.quantity_on_hand <= i.low_stock_threshold
    ) order by i.category, i.name)
    from public.inventory_items i
    where i.restaurant_id = session_row.restaurant_id),
    '[]'::jsonb
  );
end;
$$;

create or replace function public.create_inventory_item(p_session_token text, p_item jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  new_id bigint;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  insert into public.inventory_items (
    restaurant_id, name, category, unit,
    quantity_on_hand, low_stock_threshold, cost_per_unit, supplier
  )
  values (
    session_row.restaurant_id,
    trim(p_item->>'name'),
    coalesce(nullif(trim(coalesce(p_item->>'category','')), ''), 'General'),
    coalesce(nullif(trim(coalesce(p_item->>'unit','')), ''), 'pcs'),
    coalesce((p_item->>'quantityOnHand')::numeric, 0),
    coalesce((p_item->>'lowStockThreshold')::numeric, 10),
    coalesce((p_item->>'costPerUnit')::numeric, 0),
    nullif(trim(coalesce(p_item->>'supplier','')), '')
  )
  returning id into new_id;

  return jsonb_build_object('id', new_id);
end;
$$;

create or replace function public.update_inventory_item(p_session_token text, p_id bigint, p_item jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  update public.inventory_items i
  set name = coalesce(nullif(trim(p_item->>'name'),''), i.name),
      category = coalesce(nullif(trim(p_item->>'category'),''), i.category),
      unit = coalesce(nullif(trim(p_item->>'unit'),''), i.unit),
      quantity_on_hand = coalesce((p_item->>'quantityOnHand')::numeric, i.quantity_on_hand),
      low_stock_threshold = coalesce((p_item->>'lowStockThreshold')::numeric, i.low_stock_threshold),
      cost_per_unit = coalesce((p_item->>'costPerUnit')::numeric, i.cost_per_unit),
      supplier = coalesce(p_item->>'supplier', i.supplier)
  where i.id = p_id and i.restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then raise exception 'Inventory item not found.'; end if;

  return jsonb_build_object('id', p_id);
end;
$$;

create or replace function public.adjust_inventory_stock(
  p_session_token text, p_id bigint, p_delta numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  new_qty numeric;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  update public.inventory_items
  set quantity_on_hand = greatest(0, quantity_on_hand + p_delta),
      last_restocked_at = case when p_delta > 0 then now() else last_restocked_at end
  where id = p_id and restaurant_id = session_row.restaurant_id
  returning quantity_on_hand into new_qty;

  get diagnostics affected = row_count;
  if affected = 0 then raise exception 'Inventory item not found.'; end if;

  return jsonb_build_object('id', p_id, 'quantityOnHand', new_qty);
end;
$$;

create or replace function public.delete_inventory_item(p_session_token text, p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  delete from public.inventory_items
  where id = p_id and restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then raise exception 'Inventory item not found.'; end if;

  return jsonb_build_object('id', p_id, 'deleted', true);
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff CRUD + clock in/out
-- ---------------------------------------------------------------------------
create or replace function public.list_staff(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  return coalesce(
    (select jsonb_agg(jsonb_build_object(
      'id', sm.id, 'name', sm.name, 'role', sm.role,
      'phone', sm.phone, 'hourlyRate', sm.hourly_rate,
      'isActive', sm.is_active, 'hiredAt', sm.hired_at,
      'activeShiftId', (
        select sh.id from public.shifts sh
        where sh.staff_member_id = sm.id and sh.clock_out is null
        order by sh.clock_in desc limit 1
      ),
      'clockedInAt', (
        select sh.clock_in from public.shifts sh
        where sh.staff_member_id = sm.id and sh.clock_out is null
        order by sh.clock_in desc limit 1
      )
    ) order by sm.name)
    from public.staff_members sm
    where sm.restaurant_id = session_row.restaurant_id),
    '[]'::jsonb
  );
end;
$$;

create or replace function public.create_staff_member(p_session_token text, p_member jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  new_id bigint;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  insert into public.staff_members (
    restaurant_id, name, role, phone, hourly_rate, is_active, hired_at
  )
  values (
    session_row.restaurant_id,
    trim(p_member->>'name'),
    coalesce(nullif(trim(coalesce(p_member->>'role','')), ''), 'server'),
    nullif(trim(coalesce(p_member->>'phone','')), ''),
    nullif((p_member->>'hourlyRate')::text, '')::numeric,
    coalesce((p_member->>'isActive')::boolean, true),
    coalesce(nullif(p_member->>'hiredAt','')::date, current_date)
  )
  returning id into new_id;

  return jsonb_build_object('id', new_id);
end;
$$;

create or replace function public.update_staff_member(p_session_token text, p_id bigint, p_member jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  update public.staff_members sm
  set name = coalesce(nullif(trim(p_member->>'name'),''), sm.name),
      role = coalesce(nullif(trim(p_member->>'role'),''), sm.role),
      phone = coalesce(p_member->>'phone', sm.phone),
      hourly_rate = coalesce(nullif((p_member->>'hourlyRate')::text,'')::numeric, sm.hourly_rate),
      is_active = coalesce((p_member->>'isActive')::boolean, sm.is_active)
  where sm.id = p_id and sm.restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then raise exception 'Staff member not found.'; end if;

  return jsonb_build_object('id', p_id);
end;
$$;

create or replace function public.delete_staff_member(p_session_token text, p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  delete from public.staff_members
  where id = p_id and restaurant_id = session_row.restaurant_id;

  get diagnostics affected = row_count;
  if affected = 0 then raise exception 'Staff member not found.'; end if;

  return jsonb_build_object('id', p_id, 'deleted', true);
end;
$$;

create or replace function public.clock_in_staff(p_session_token text, p_staff_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  new_shift_id bigint;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  if exists (
    select 1 from public.shifts
    where staff_member_id = p_staff_id and clock_out is null
  ) then
    raise exception 'Staff member is already clocked in.';
  end if;

  insert into public.shifts (staff_member_id, restaurant_id, clock_in)
  values (p_staff_id, session_row.restaurant_id, now())
  returning id into new_shift_id;

  return jsonb_build_object('shiftId', new_shift_id, 'clockIn', now());
end;
$$;

create or replace function public.clock_out_staff(p_session_token text, p_shift_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
  affected integer;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  update public.shifts
  set clock_out = now()
  where id = p_shift_id
    and restaurant_id = session_row.restaurant_id
    and clock_out is null;

  get diagnostics affected = row_count;
  if affected = 0 then raise exception 'Shift not found or already closed.'; end if;

  return jsonb_build_object('shiftId', p_shift_id, 'clockOut', now());
end;
$$;

create or replace function public.get_active_shifts(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  session_row record;
begin
  select s.admin_id, s.restaurant_id, s.email, s.role
  into session_row
  from public._require_admin_session(p_session_token) s;

  return coalesce(
    (select jsonb_agg(jsonb_build_object(
      'shiftId', sh.id, 'staffId', sm.id, 'staffName', sm.name,
      'role', sm.role, 'clockIn', sh.clock_in, 'clockOut', sh.clock_out,
      'hoursWorked', case
        when sh.clock_out is not null
        then round(extract(epoch from (sh.clock_out - sh.clock_in)) / 3600, 2)
        else round(extract(epoch from (now() - sh.clock_in)) / 3600, 2)
      end
    ) order by sh.clock_in desc)
    from public.shifts sh
    join public.staff_members sm on sm.id = sh.staff_member_id
    where sh.restaurant_id = session_row.restaurant_id
      and sh.clock_in >= date_trunc('day', now())),
    '[]'::jsonb
  );
end;
$$;

-- RLS for new tables
alter table public.reservations enable row level security;
alter table public.inventory_items enable row level security;
alter table public.staff_members enable row level security;
alter table public.shifts enable row level security;

revoke all on public.reservations from anon, authenticated;
revoke all on public.inventory_items from anon, authenticated;
revoke all on public.staff_members from anon, authenticated;
revoke all on public.shifts from anon, authenticated;

grant execute on function public.create_pos_order(text, jsonb) to anon, authenticated;
grant execute on function public.update_table_status(text, bigint, text) to anon, authenticated;
grant execute on function public.list_reservations(text, date, date) to anon, authenticated;
grant execute on function public.create_reservation(text, jsonb) to anon, authenticated;
grant execute on function public.update_reservation_status(text, bigint, text) to anon, authenticated;
grant execute on function public.delete_reservation(text, bigint) to anon, authenticated;
grant execute on function public.list_inventory(text) to anon, authenticated;
grant execute on function public.create_inventory_item(text, jsonb) to anon, authenticated;
grant execute on function public.update_inventory_item(text, bigint, jsonb) to anon, authenticated;
grant execute on function public.adjust_inventory_stock(text, bigint, numeric) to anon, authenticated;
grant execute on function public.delete_inventory_item(text, bigint) to anon, authenticated;
grant execute on function public.list_staff(text) to anon, authenticated;
grant execute on function public.create_staff_member(text, jsonb) to anon, authenticated;
grant execute on function public.update_staff_member(text, bigint, jsonb) to anon, authenticated;
grant execute on function public.delete_staff_member(text, bigint) to anon, authenticated;
grant execute on function public.clock_in_staff(text, bigint) to anon, authenticated;
grant execute on function public.clock_out_staff(text, bigint) to anon, authenticated;
grant execute on function public.get_active_shifts(text) to anon, authenticated;

-- Seed inventory for restaurant 1
insert into public.inventory_items
  (restaurant_id, name, category, unit, quantity_on_hand, low_stock_threshold, cost_per_unit, supplier)
select * from (values
  (1,'All-Purpose Flour','Dry Goods','kg',45,10,180,'Al-Ghazali Mills'),
  (1,'Chicken Breast','Proteins','kg',8,5,750,'Fresh Direct'),
  (1,'Parmesan','Dairy','kg',2,3,1200,'Imported Deli'),
  (1,'Pasta (Fettuccine)','Dry Goods','kg',12,5,300,'Al-Ghazali Mills'),
  (1,'Olive Oil','Condiments','L',6,2,850,'Mediterranean Imports'),
  (1,'Heavy Cream','Dairy','L',3,2,450,'Fresh Direct'),
  (1,'Tarragon (Fresh)','Herbs','g',120,50,600,'Green Farms'),
  (1,'Salt','Condiments','kg',8,2,60,'Local'),
  (1,'Black Pepper','Condiments','g',400,100,900,'Spice Route')
) as seed(restaurant_id, name, category, unit, qty, threshold, cost, supplier)
where not exists (select 1 from public.inventory_items where restaurant_id = 1);

insert into public.inventory_items
  (restaurant_id, name, category, unit, quantity_on_hand, low_stock_threshold, cost_per_unit, supplier)
select * from (values
  (2,'Chicken Breast','Proteins','kg',6,5,750,'Fresh Direct'),
  (2,'Parmesan','Dairy','kg',4,3,1200,'Imported Deli'),
  (2,'Pasta (Fettuccine)','Dry Goods','kg',10,5,300,'Al-Ghazali Mills'),
  (2,'Tarragon (Fresh)','Herbs','g',80,50,600,'Green Farms')
) as seed(restaurant_id, name, category, unit, qty, threshold, cost, supplier)
where not exists (select 1 from public.inventory_items where restaurant_id = 2);

-- Seed staff for restaurant 1
insert into public.staff_members (restaurant_id, name, role, phone, hourly_rate, is_active, hired_at)
select * from (values
  (1,'Ahmed Malik','head_chef','+92-300-1234567',550,'2023-03-01'),
  (1,'Sara Khan','server','+92-301-2345678',280,'2023-06-15'),
  (1,'Bilal Qureshi','server','+92-302-3456789',280,'2024-01-10'),
  (1,'Fatima Raza','kitchen_staff','+92-303-4567890',320,'2023-09-20'),
  (1,'Omar Sheikh','manager','+92-304-5678901',500,'2022-12-01')
) as seed(restaurant_id, name, role, phone, hourly_rate, hired_at)
where not exists (select 1 from public.staff_members where restaurant_id = 1);
